spring:
  cloud:
    bus:
      trace:
        enabled: true
    stream:
      instanceCount: 3
      instanceIndex: 0
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}

management:
  security:
    enabled: false

---
spring.profiles: docker

spring:
  cloud:
    bus:
      trace:
        enabled: true
    stream:
      instanceCount: 3
      instanceIndex: 0
      kafka:
        binder:
          brokers: kafka:9092
          zk-nodes: zk:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
    config:
      server:
        git:
          uri: ${ALAUDA_GIT:https://github.com/microServiceTest/{application}}
          username: ${ALAUDA_GIT_USER}
          password: ${ALAUDA_GIT_PASSWORD}

management:
  port: 9876
