spring:
  rabbitmq:
    host: localhost
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}

management:
  port: 9876
  security:
    enabled: false

---
spring.profiles: docker

spring:
  rabbitmq:
    host: rabbitmq
  cloud:
    config:
      server:
        git:
          uri: ${ALAUDA_GIT:https://github.com/microServiceTest/{application}}
          username: ${ALAUDA_GIT_USER}
          password: ${ALAUDA_GIT_PASSWORD}