management:
  security:
    enabled: false

logging:
  level:
    ROOT: INFO
    org.springframework.security: DEBUG
    
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current

spring:
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    bus:
      trace:
        enabled: true
    stream:
      instanceCount: 3
      instanceIndex: 0
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true

---
spring.profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

spring:
  zipkin:
      base-url: http://zipkin:9411
  cloud:
    bus:
      trace:
        enabled: true
    stream:
      instanceCount: 3
      instanceIndex: 0
      kafka:
        binder:
          brokers: kafka:9092
          zk-nodes: zk:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true

management:
  port: 9876